 <head>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>app/style/basic.css">>
</head>
<form  method="POST">
    <div class="row">
        <div  class="form-group">
                <label>Titulo libro</label>
                <input required name="titulo" type="text">
        </div>

        <div>
            <div class="form-group" >
                <label>Genero</label>
                <select required name="genero">
                    <option value="1">romance</option>
                    <option value="2">terror</option>
                    <option value="3">fantasia</option>

                </select>
            </div>
        </div>
    </div>

    <div >
        <label class="form-group">Autor</label>
        <textarea name="autor"></textarea>
    </div>

    <button type="submit">Guardar Libro</button>
</form>