<?php require_once 'app/templates/header.phtml'; ?>

<div class="container">
    <form action="<?php echo BASE_URL . 'verifylogin'; ?>" method="POST" class="login-form">
        <h1>Iniciar Sesión</h1>

        <?php if (!empty($error)): ?>
            <p class="error-message"><?php echo htmlspecialchars($error); ?></p>
        <?php endif; ?>

        <div class="form-group">
            <label>Email o Usuario</label>
            <input required name="email" type="email">
        </div>

        <div class="form-group">
            <label >Contraseña</label>
            <input  required  name="contraseña" type="password" placeholder="Ingresa tu contraseña"
            >
        </div>
        
        <button type="submit">Entrar</button>

    </form>
</div>

