
     <head>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>app/style/basic.css">>
</head>
    
<?php
require_once 'app/helpers/authhelper.php';
$isLogged = AuthHelper::isLogged(); 
$userName = $_SESSION['USER_NAME'] ?? 'Admin';
?>
<body>

    <header class="header">
        
        <nav>
            <a href="<?php echo BASE_URL . 'listarlibros'; ?>" class="nav-link">Libros:</a>
            
            <?php if ($isLogged): ?>
                <span class="adminsection">
                    Hola, <?php echo htmlspecialchars($userName); ?>
                    |
                    <a href="<?php echo BASE_URL . 'logout'; ?>" class="btn-logout">Cerrar Sesión</a>
                </span>
            <?php endif; ?>
        </nav>
    </header>