<main class="container detalle-libro">
    
    <?php if (empty($libro)): ?>
        <div class="error">
            <p>El libro que intenta ver no fue encontrado.</p>
            <p><a href="<?php echo BASE_URL . 'listarlibros'; ?>">Volver al listado</a></p>
        </div>
        
    <?php else: ?>
        
        <h1 class="titulo-">Titulo: <?= htmlspecialchars($libro->nombre_persona) ?></h1>
        
        <div class="fichalibro">
            
            <p><strong>Autor:</strong> 
                <?= htmlspecialchars($libro->autor) ?>
            </p>
            <p><strong>Lo Posee:</strong>
                <a href="<?= BASE_URL . 'librospertenecientes/' . htmlspecialchars($libro->{'id-persona'}, ENT_QUOTES, 'UTF-8') ?>">
                    <?= htmlspecialchars($libro->nombre_persona) ?>
                </a>
            </p>
                <h2>Descripción</h2>
                <p> <?=htmlspecialchars($libro->descripcion) ?></p>
         
               <?php if ($islogged): ?>
                <div class="adminactions">
                    <a href="<?= BASE_URL . 'editarlibro/' . htmlspecialchars($libro->id) ?>" class="btn-editar">
                        Editar Libro
                    </a>
                    <a href="<?= BASE_URL . 'borrarlibro/' . htmlspecialchars($libro->id) ?>" class="btn-eliminar">
                        Eliminar Libro
                    </a>
                </div>
            <?php endif; ?>
            
        </div>
    <?php endif; ?>
    
</main>