<?php if (!empty($libros)): ?>
    <ul class="listalibros">
        <?php foreach ($libros as $libro): ?>
            <li class="libro">
                
                <a href="<?php echo BASE_URL . 'mostrarlibro/' . $libro->id; ?>">
                    <h2><?php echo htmlspecialchars($libro->nombre); ?></h2> 
                </a>
                
                <p>Autor: <?php echo htmlspecialchars($libro->autor); ?></p>
                
                <p>Género: <a href="<?php echo BASE_URL . 'libros_por_genero/' . $libro->id_genero; ?>"><?php echo htmlspecialchars($libro->nombre_genero); ?> </a></p>
                            
                <?php if ($islogged): ?>
                    <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>