
<?php require_once 'app/templates/header.phtml'; ?>

<div class="container">
    
    <?php if (isset($libro) && $libro): ?>
        <article class="libro-detalle">
            <li class="libro">
                <a href="<?php echo BASE_URL . 'mostrarlibro/' . $libro->id; ?>">
                    <h2><?php echo htmlspecialchars($libro->titulo); ?></h2> 
                </a>

                <p>Autor: <?php echo htmlspecialchars($libro->autor); ?></p>
                <p>Género: <a href="<?php echo BASE_URL . 'librosporgenero/' . $libro->id_genero; ?>"><?php echo htmlspecialchars($libro->nombre_genero); ?> </a></p>
                <p>Descripcion: <?php echo htmlspecialchars($libro->descripcion); ?></p>
                <?php if (isset($user) && $user): ?> 
                    <div class="actions list-actions">
                        <a href="<?php echo BASE_URL . 'editar/' . $libro->id; ?>" class="button-action-link button-edit">Editar</a> 
                        |
                        <a href="<?php echo BASE_URL . 'borrarlibro/' . $libro->id; ?>" class="button-action-link button-delete">Borrar</a>
                    </div>
                <?php endif; ?>
            </li>
        </ul>
    <?php endif; ?>
           
           
            <a href="<?php echo BASE_URL . 'listarlibros'; ?>" class="button">
                Volver al Listado
            </a>

        </article>
   
    
</div>



